// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace InstrumentProtocol
{

public enum CommandCode : sbyte
{
  Start = 0,
  Stop = 1,
};


}
