// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace InstrumentProtocol
{

public enum MessageType : byte
{
  NONE = 0,
  Command = 1,
  Configuration = 2,
  Measurement = 3,
};



static public class MessageTypeVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((MessageType)typeId)
    {
      case MessageType.Command:
        result = InstrumentProtocol.CommandVerify.Verify(verifier, tablePos);
        break;
      case MessageType.Configuration:
        result = InstrumentProtocol.ConfigurationVerify.Verify(verifier, tablePos);
        break;
      case MessageType.Measurement:
        result = InstrumentProtocol.MeasurementVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
